# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WC-vphz__tAFgkPdwHqEgMm8o6KAcOqU
"""

!pip install buildozer

!pip install cython==0.29.19

!sudo apt-get install -y \
python3-pip \
git \
python3 \
python3-dev \
ffmpeg \
libsdl2-dev \
libsdl2-image-dev \
libsdl2-mixer-dev \
libsdl2-ttf-dev \
libportmidi-dev \
libswscale-dev \
libavformat-dev \
libavcodec-dev \
zlib1g-dev

!sudo apt-get update

!apt-cache search libffi

!sudo apt-get install libffi-dev

!sudo apt-get install build-essential libsqlite3-dev sqlite3 \
bzip2 libbz2-dev zlib1g-dev libssl-dev openssl libgdbm-dev \
libgdbm-compat-dev liblzma-dev libreadline-dev libncursesw5-dev \
libffi-dev uuid-dev libffi6

!sudo apt-get install libffi-dev
!sudo apt update && sudo apt install -y libffi-dev

!sudo apt update
!sudo apt install -y git zip unzip openjdk-17-jdk python3-pip python3-venv libffi-dev libssl-dev build-essential
!pip install --upgrade pip setuptools cython virtualenv
!pip install --upgrade buildozer python-for-android kivy kivymd

"""Make these changes in buildoze.spec file under line 37 # (list) Application requirements
# comma separated e.g. requirements = sqlite3,kivy
requirements = python3,kivy==2.0.0,kivymd,pillow
"""

!buildozer init

"""requirements = python3,kivy,kivymd"""

import sys
print(sys.version)

!rm -rf .buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build
!rm -rf .buildozer/android/platform/build-arm64-v8a_armeabi-v7a/dists
!buildozer -v android debug

!buildozer -v android debug

